import "./APIs";
import "./bootstrap";
import "./error";
import Router from "./router";
import "./sentry";
import "./v-tooltip";
import "./vee-validate";
import "./vue-backtotop";
import "./vue-countdown";
import "./vue-flip";
import "./vue-github-buttons";
import "./vue-gtag";
import i18n from "./vue-i18n";
import "./vue-js-toggle-button";
import "./vue-keypress";
import "./vue-lazyload";
import "./vue-meta";
import "./vue-particles";
import "./vue-roller";
import "./vue-scrollto";
import "./vue-select";
import "./vue-star-rating";
import "./vue-toasted";
import "./vue-tour";

export { Router, i18n };